### ISSUE TITLE
Async initiliazations

### ISSUE THREAD

**Issue by davidmanzanares** [IagoLast/falcon-benchmark#1]
Is there a way to do asynchronous initializations like loading a file before the benchmarks?

If not, I'd be happy to do it, but some guidance would be helpful.

cc: @IagoLast

**Comment by davidmanzanares** [comment]
I read the new `before` hook, it looks like that's what I need, but I was not able to make it work:
```

let str = 'still this';

falcon.benchmark('decodePolygon', () => {
    console.log(str);
}, {runs: 1,
    before: () => {
        str = 'it works!';
    }});

```
Output:
```
still this
still this
```

**Comment by IagoLast** [comment]
Reinstall the package, ensure you have the `0.1.1-1 version`

**Comment by davidmanzanares** [comment]
Solved

**Comment by davidmanzanares** [comment]
Now I see the original problem again, I have a hook, but I don't have a way to do async operations there, right? Do I receive a `done`? May I return a promise?

**Comment by IagoLast** [comment]
return a promise

**Comment by davidmanzanares** [comment]
:+1:
